---
- name: Configurar y desplegar MySQL
  hosts: mysql
  become: true

  tasks:
    # - name: Detener el servicio MySQL si está en ejecución
    #   systemd:
    #     name: mysql
    #     state: stopped

    # Purga todos los paquetes de MySQL, incluyendo versiones específicas
    - name: Purga todos los paquetes de MySQL
      apt:
        name:
          - mysql-server        # Paquete principal de MySQL
          - mysql-client         # Cliente de MySQL
          - mysql-common          # Paquete común de MySQL
          - mysql-server-core-*    # Remueve todas las versiones de MySQL core
          - mysql-client-core-*     # Remueve todas las versiones de MySQL client core
          - mysql-server-5.7       # Versión específica que deseas eliminar
          - mysql-server-8.0       # Otra versión específica a eliminar
        state: absent

    # Elimina todas las configuraciones y datos de MySQL
    - name: Eliminar las carpetas de configuración y datos de MySQL
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/mysql          # Configuraciones de MySQL
        - /var/lib/mysql      # Datos de MySQL
        - /var/log/mysql      # Registros de MySQL

    # Limpia paquetes no necesarios
    - name: Limpiar paquetes no necesarios
      apt:
        autoremove: yes
        autoclean: yes

    # Actualiza los repositorios
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    # Instala MySQL
    - name: Instalar MySQL
      apt:
        name: mysql-server  # Este comando instalará la versión más reciente de MySQL
        state: present

    # Configura MySQL para que escuche solo en localhost
    - name: Configurar MySQL para que escuche solo en localhost
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 127.0.0.1'

    # Reinicia el servicio MySQL
    - name: Reiniciar MySQL
      service:
        name: mysql
        state: restarted

    # Crea base de datos
    - name: Crear base de datos
      mysql_db:
        name: testdb
        state: present

    # Crea un usuario en MySQL
    - name: Crear usuario MySQL
      mysql_user:
        name: root
        password: "123456"
        priv: "testdb.*:ALL"
        host: "localhost"
        state: present
