---
- name: Configure MySQL User and Database on DigitalOcean Droplet
  hosts: mysql
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"  # Asegúrate de usar el intérprete correcto
    mysql_root_password: "1d1cfe5d5a721e5281cc4d3189f003ea30b8edffc85c471d"  # Contraseña de root que te dio la consola
    mysql_user: "admin"  # Usuario MySQL que te dio la consola
    mysql_password: "af2547750c3137ef873ca465910310f82bd1d60721ad1e7e"  # Contraseña del usuario admin que te dio la consola
    mysql_database: "testdb"  # Base de datos que quieres crear

  tasks:
    - name: Update apt cache (si es necesario)
      apt:
        update_cache: yes


    - name: Install MySQL-python
      apt:
        name: python3-mysqldb
        state: present

        
          
    # No instalamos MySQL ya que ya está preinstalado en la imagen One-Click

    - name: Ensure MySQL is running and enabled at startup
      service:
        name: mysql
        state: started
        enabled: yes

    # Crea la base de datos
    - name: Crear base de datos
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    # Crea un usuario en MySQL con acceso a la base de datos
    - name: Crear usuario MySQL
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: "localhost"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    # Crea la tabla en la base de datos
    - name: Crear tabla en la base de datos
      mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_db: "{{ mysql_database }}"
        query: |
          CREATE TABLE IF NOT EXISTS `tutorials` (
            id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
            title VARCHAR(255) NOT NULL,
            description VARCHAR(255),
            published BOOLEAN DEFAULT FALSE
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
